version: '3'
services:
  app:
    image: jc21/nginx-proxy-manager:2
    restart: always
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./config.json:/app/config/production.json
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    environment:
    # if you want pretty colors in your docker logs:
    - FORCE_COLOR=1
  db:
    image: jc21/mariadb-aria
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "09123hjasaSDQWjadASd___sadasm_-123a2saZXqdFAn2112312"
      MYSQL_DATABASE: "nginxproxymanager"
      MYSQL_USER: "nginxproxymanager"
      MYSQL_PASSWORD: "09123hjasaSDQWjadASd___sadasm_-123a2saZXqdFAn2112312"
    volumes:
      - ./data/mysql:/var/lib/mysql
  server:
    build: .
    image: graphql-server
    restart: on-failure
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - prisma
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
  prisma:
    image: prismagraphql/prisma:1.30
    restart: on-failure
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: c005c2c56677f225b0e0c28420e31aa8b8a35476
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
            rawAccess: true
  postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
