version: '3'
services:
  server:
    build: .
    image: graphql-server
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - prisma
    volumes:
      - ./:/usr/src/app
  prisma:
    image: prismagraphql/prisma:1.29
    restart: on-failure
    ports:
    - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
            rawAccess: true
  postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: